name: Actions

on:
  schedule:
    - cron: 0 8 * * *
  push:
    branches:
      - master

jobs:
  update-readme:
    name: Update kwaa/README.md
    runs-on: ubuntu-latest
    steps:
      - name: Update latest posts
        uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://blog.917.moe/atom.xml
          readme-section: posts
          max: 5
      - name: Update readme comment
        uses: actions/github-script@v2
        with:
          script: |
            github.issues.listComments({
              kwaa,
              blog,
              6
            })