name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  update-readme:
    name: Update kwaa/README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "README.tpl.md"
          writeTo: "README.md"
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update kwaa/README
          branch: main
